# Load in NumPy
(Remember to pip install numpy first)

In [2]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

#### The Basics

In [4]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])

In [6]:
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get dimension
a.ndim

1

In [8]:
b.ndim

2

In [9]:
# Get shape
a.shape

(3,)

In [10]:
b.shape

(2, 3)

In [11]:
# Get type
a.dtype

dtype('int32')

In [13]:
b.dtype

dtype('float64')

In [14]:
# Get size
a.itemsize

4

In [15]:
b.itemsize

8

In [17]:
# Get total size
a.nbytes

12

In [18]:
b.nbytes

48