#### Accessing/Changing specific elements, rows, columns, etc.

In [1]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [4]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [5]:
# Get specific element [r, c]
a[1, 5]

13

In [6]:
# Get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
# Get specific column
a[:, 2]

array([ 3, 10])

In [9]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [10]:
a[0, 1:6:-2]

array([], dtype=int32)

In [11]:
a[0, 1:-1:2]

array([2, 4, 6])

In [12]:
# Change an element
a[1, 5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [13]:
a[:, 2] = 5

In [14]:
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

#### 3-d example

In [16]:
b = np.array([ [[1, 2], [3, 4]], [[5, 6], [7, 8]] ])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [17]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

In [18]:
b[:, 1, :] = [[9, 9], [8, 8]]

In [19]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])