# Initializing Different Arrays

In [1]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
# All 0s matrix 
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
# All 1s matrix
np.ones((4, 2, 2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [5]:
# Any other number
np.full((2,2), 99, dtype="float32")

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [6]:
# Any other number (full_like)
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [7]:
# Random decimal numbers
np.random.rand(4, 2)

array([[0.05285126, 0.64906204],
       [0.69617385, 0.43785222],
       [0.6514614 , 0.07988737],
       [0.64932716, 0.96813386]])

In [8]:
np.random.random_sample(a.shape)

array([[0.61931409, 0.20310748, 0.93634516, 0.19313462, 0.67321694,
        0.55020156, 0.10091242],
       [0.56247976, 0.38818875, 0.33437119, 0.67341366, 0.54052266,
        0.06833059, 0.30165706]])

In [9]:
# Random Integer values
np.random.randint(7, size=(3,3))

array([[2, 0, 3],
       [3, 0, 3],
       [4, 4, 1]])

In [10]:
np.random.randint(-4, 8, size=(3,3))

array([[-4,  7, -2],
       [-3,  7,  5],
       [-2,  2,  0]])

In [11]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
# Repeat an array
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [13]:
output = np.ones((5, 5))
print(output)

z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Copying Arrays Warning

#### Be careful when copying arrays!

In [14]:
a = np.array([1, 2, 3])
b = a
b

array([1, 2, 3])

In [15]:
b[0] = 100

In [16]:
print(b)

[100   2   3]


In [17]:
print(a)

[100   2   3]


Changing `b` also affects `a`

In [18]:
a = np.array([1, 2, 3])
b = a.copy()

print(a)
print(b)

[1 2 3]
[1 2 3]


In [19]:
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]
