# Mathematics

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
a + 2

array([3, 4, 5, 6])

In [5]:
a - 1

array([0, 1, 2, 3])

In [6]:
a * 2

array([2, 4, 6, 8])

In [7]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [8]:
b = np.array([1, 0, 1, 0])
a+b

array([2, 2, 4, 4])

In [9]:
a ** 2

array([ 1,  4,  9, 16])

In [10]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [11]:
# for a lot more (https://docs.scipy.org/doc/numpy/reference/routimes.math.html")

#### Linear Algebra

In [12]:
a = np.full((2, 3), 2)
print(a)

b = np.full((3, 2), 2)
print(b)

[[2 2 2]
 [2 2 2]]
[[2 2]
 [2 2]
 [2 2]]


In [13]:
np.matmul(a, b)

array([[12, 12],
       [12, 12]])

In [14]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [15]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Value Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# etc...


#### Statistics

In [16]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.min(stats, axis = 1)

array([1, 4])

In [18]:
np.min(stats, axis=0)

array([1, 2, 3])

In [19]:
np.min(stats)

1

In [20]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [21]:
np.max(stats, axis=1)

array([3, 6])

In [22]:
np.max(stats)

6

In [23]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [24]:
np.sum(stats, axis=1)

array([ 6, 15])

In [25]:
np.sum(stats)

21