# Reorganizing Arrays

In [1]:
import numpy as np

In [2]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [3]:
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
before.shape

(2, 4)

In [5]:
after = before.reshape((8, 1))

In [6]:
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [7]:
after = before.reshape((2, 2, 2))

In [8]:
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7,8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
# Horizontal stack
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))


In [12]:
h1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
h2

array([[0., 0.],
       [0., 0.]])

In [14]:
np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])